"""Generate TypeScript assets for the M3 port from Python sources.

    python gen_ts_assets.py --repo ~/workspace/blockingmachine

Writes into packages/core:
  src/ai/learned/featureSpec.ts   - version, names, tokens, TLD sets, bigram table
  ai-weights/model.json           - copy of the exported bm-gbdt/1 artifact
  ai-weights/allowlist.json       - copy of the exported bm-allowlist/1 artifact
  src/__tests__/fixtures/learned-fixtures.json   - copy of fixtures.json
  src/__tests__/fixtures/learned-expected-scores.json - Python reference scores
  src/__tests__/fixtures/learned-ip-battery.json      - ipaddress verdicts

Run from the training venv (needs lightgbm for reference scores).
Re-run after any retrain; the jest parity test fails if assets drift.
"""
from __future__ import annotations

import argparse
import ipaddress
import json
import math
import shutil
from pathlib import Path

import lightgbm as lgb

from export import predict_one, convert_node
from features import FEATURE_NAMES, FEATURE_VERSION, featurize_vector
from features2 import FEATURE_NAMES as FEATURE_NAMES_V2, N_V1
from features2 import FEATURE_VERSION as FEATURE_VERSION_V2
from features2 import featurize_vector_v2, load_observations
from tokens import COMMON_TLDS, SUSPICIOUS_TLDS, TOKEN_LIST

HERE = Path(__file__).resolve().parent

# Domains spanning the decision space, for end-to-end TS parity.
SCORE_DOMAINS = [
    "cm.g.doubleclick.net",      # canonical tracker
    "adserver.bidding.adtech.net",
    "xzk7q92bwa1m.com",          # DGA-ish
    "free-spins.buzz",           # suspicious TLD
    "github.com",                # benign
    "paypal.com",                # benign, financial
    "fonts.gstatic.com",         # golden allowlist, scores high
    "login.microsoftonline.com", # golden allowlist, scores high
]

# Tricky inputs for the ip_literal port (Python ipaddress is the oracle).
IP_BATTERY = [
    "1.2.3.4", "255.255.255.255", "0.0.0.0",
    "01.2.3.4",          # leading zeros -> NOT an IP per ipaddress
    "1.2.3.256",         # octet out of range
    "1.2.3", "1.2.3.4.5",
    "::1", "2001:db8::1", "fe80::1",
    "::ffff:1.2.3.4",    # ipv4-mapped
    "2001:db8:::1",      # invalid
    "github.com", "1234.com",
]


def ts_string_list(items: list[str]) -> str:
    return "[\n" + "".join(f"  {json.dumps(s)},\n" for s in items) + "]"


def ts_string_set(items: set[str]) -> str:
    return "new Set([\n" + "".join(f"  {json.dumps(s)},\n" for s in sorted(items)) + "])"


def gen_feature_spec() -> str:
    table = json.loads((HERE / "bigram_table.json").read_text())["log_probs"]
    lines = [
        "/**",
        " * Feature spec for the learned GBDT classifier (schemas v1 + v2).",
        " *",
        " * GENERATED by gen_ts_assets.py from tokens.py + features2.py +",
        " * bigram_table.json. Do not edit by hand. Changing any list, the",
        " * bigram table, or the feature order changes the model contract:",
        " * bump the version and retrain instead.",
        " */",
        "",
        "/** Lexical-only feature contract version (v1 model.json). */",
        f"export const LEARNED_FEATURE_VERSION = {FEATURE_VERSION};",
        "",
        "/** Behavioral feature contract version (v2 model.json). */",
        f"export const LEARNED_FEATURE_VERSION_V2 = {FEATURE_VERSION_V2};",
        "",
        "/** Number of lexical features: the v1 prefix of every v2 vector. */",
        f"export const LEARNED_V1_FEATURE_COUNT = {N_V1};",
        "",
        "/** Fixed order: position i in the v1 vector is LEARNED_FEATURE_NAMES[i]. */",
        f"export const LEARNED_FEATURE_NAMES: readonly string[] = {ts_string_list(FEATURE_NAMES)};",
        "",
        "/** v2 order: v1 prefix + behavioral features (NaN when unobserved). */",
        f"export const LEARNED_FEATURE_NAMES_V2: readonly string[] = {ts_string_list(FEATURE_NAMES_V2)};",
        "",
        "/** Tracker/advertising vocabulary, matched as case-insensitive substrings. */",
        f"export const LEARNED_TOKENS: readonly string[] = {ts_string_list(TOKEN_LIST)};",
        "",
        "/** TLDs treated as common (tld_rarity = 0). */",
        f"export const LEARNED_COMMON_TLDS: ReadonlySet<string> = {ts_string_set(COMMON_TLDS)};",
        "",
        "/** TLDs treated as suspicious (tld_suspicious = 1). */",
        f"export const LEARNED_SUSPICIOUS_TLDS: ReadonlySet<string> = {ts_string_set(SUSPICIOUS_TLDS)};",
        "",
        "/**",
        " * Background bigram model: natural-log P(bigram) with Laplace smoothing,",
        " * over alphabet [a-z0-9-.]. bigram_anomaly = mean(-log P) over the",
        " * domain's bigrams. Parsed from the same decimals Python wrote, so",
        " * the doubles are bit-identical.",
        " */",
        "export const LEARNED_BIGRAM_LOG_PROBS: Readonly<Record<string, number>> = {",
    ]
    for bg in sorted(table):
        lines.append(f"  {json.dumps(bg)}: {table[bg]!r},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def gen_v2_fixtures(observations_db: str, fixtures_dir: Path, n: int = 8) -> None:
    """v2 parity fixtures: observed domains + TS-shaped obs + expected vectors.

    JSON has no NaN, so missing behavioral values serialize as null;
    the jest test maps null -> NaN before comparing.
    """
    import sqlite3  # noqa: F401  (load_observations handles the read)

    obs = load_observations(observations_db)
    out = []
    for d in sorted(obs)[:n]:
        row = obs[d]

        def b(col: str) -> bool | None:
            v = row[col]
            return None if v is None else bool(v)

        ts_obs = {
            "redirectCount": row["redirect_count"],
            "fetchError": row["fetch_error"] is not None,
            "hasSetCookie": b("set_cookie"),
            "cookieCount": row["cookie_count"],
            "bodyKeywordHits": row["body_kw_hits"],
            "httpsOk": b("https_ok"),
            "certFreeCa": b("cert_free_ca"),
            "cnameDepth": row["cname_depth"],
        }
        vec = featurize_vector_v2(d, obs)
        out.append({
            "domain": d,
            "obs": ts_obs,
            "vector": [None if math.isnan(x) else x for x in vec],
        })
    (fixtures_dir / "learned-fixtures-v2.json").write_text(json.dumps(out, indent=1))
    print(f"wrote {len(out)} v2 fixtures from {observations_db}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--observations", default=None,
                    help="observations.db; when given, also emit v2 fixtures")
    args = ap.parse_args()
    core = Path(args.repo) / "packages" / "core"
    learned = core / "src" / "ai" / "learned"
    fixtures_dir = core / "src" / "__tests__" / "fixtures"
    weights_dir = core / "ai-weights"
    learned.mkdir(parents=True, exist_ok=True)
    fixtures_dir.mkdir(parents=True, exist_ok=True)
    weights_dir.mkdir(parents=True, exist_ok=True)

    (learned / "featureSpec.ts").write_text(gen_feature_spec())
    print(f"wrote {learned / 'featureSpec.ts'}")

    for name in ("model.json",):
        shutil.copy(HERE / name, weights_dir / name)
    shutil.copy(HERE / "model_artifacts" / "allowlist.json", weights_dir / "allowlist.json")
    print(f"copied weights -> {weights_dir}")

    shutil.copy(HERE / "fixtures.json", fixtures_dir / "learned-fixtures.json")

    booster = lgb.Booster(model_file=str(HERE / "model_artifacts" / "model.txt"))
    trees = [convert_node(t["tree_structure"]) for t in booster.dump_model()["tree_info"]]
    scores = []
    for d in SCORE_DOMAINS:
        v = featurize_vector(d)
        ref = float(booster.predict([v])[0])
        mine = predict_one(trees, v)
        assert abs(ref - mine) < 1e-12, d
        scores.append({"domain": d, "score": ref})
    (fixtures_dir / "learned-expected-scores.json").write_text(
        json.dumps(scores, indent=1))
    print(f"wrote {len(scores)} expected scores")

    battery = []
    for d in IP_BATTERY:
        try:
            ipaddress.ip_address(d)
            verdict = 1.0
        except ValueError:
            verdict = 0.0
        battery.append({"domain": d, "ip_literal": verdict})
    (fixtures_dir / "learned-ip-battery.json").write_text(json.dumps(battery, indent=1))
    print(f"wrote {len(battery)} ip_literal cases")

    if args.observations:
        gen_v2_fixtures(args.observations, fixtures_dir)


if __name__ == "__main__":
    main()
