/**
 * The shipped static tiers must be things the embedded classifier can account for.
 *
 * The Mini-AI classifier is what the AI Radar reports to the user, what the triage cascade screens
 * with, and what the element picker corroborates with. The static tiers are a *separate* body of
 * knowledge — a hand-curated blocklist — and the two can drift apart in silence. When they do, the
 * extension blocks a host while the model it also ships calls that host clean, and nothing in the
 * build notices. This suite is that notice.
 *
 * It walks every domain the shipped tier files contain and fails on any disagreement with the tier
 * that ships it. What is tolerated is *measured*, never assumed, and the shape of the tolerance is
 * the finding:
 *
 *   - **The model never contradicts a tier.** Across all 118 curated hosts, not one is classified
 *     into a different blocking family without the pin recording it — no ad host called a tracker,
 *     no tracker called malware. A disagreement is either the model failing to place a host at all
 *     (`Clean`) or a *documented re-filing*: a host the model insists on under a family stricter
 *     than the tier's name, which the vocabulary record carries with the family it measured.
 *   - **It fails to place 2 of them** — 1 privacy and 1 annoyance host — always as `Clean`, under the
 *     90% mark past which a clean verdict is an assertion rather than a shrug. That is the same weak
 *     band the triage cascade escalates, so these hosts are that cascade's documented reason for
 *     existing rather than a bug in the list. The count was 46 until the classifier learned the
 *     vendors these tiers carry; 43 hosts moved out of the pin because of it, and the three that did
 *     not are the two kinds of gap that remain — see `TOLERATED_MISSES`.
 *   - **The always-on Core shield tier gets no such latitude**: every host it ships is recognised.
 *     That tier is enabled on a fresh install, so it does not get the benefit of the doubt.
 *   - **`tier_annoyances` now has a category to be measured against.** The classifier learned a real
 *     `Consent/Annoyance` family, and 20 of the tier's 22 hosts place there through the derived
 *     consent vocabulary — the tier is what taught the word. Two hosts stay on the record:
 *     `privy.com`, whose only label is an ordinary English word no derivation may mint, and
 *     `onesignal.com`, a documented re-filing — the model already knew `onesignal` as tracker
 *     infrastructure, and that stronger claim outranks the consent axis. The tier still ships
 *     disabled, and that is a product decision about what a fresh install should interrupt —
 *     consent prompts and notification flows — not a statement that the model lacks the word.
 *
 * The disagreement set is *pinned* rather than the assertion being loosened, and it has to hold its
 * own weight: 43 of the 46 original entries are gone, and every one of them left because the
 * classifier learned the vendor rather than because the pin was relaxed. What is left is pinned for
 * two different reasons and the list says which is which. A host added to a tier the model cannot
 * account for fails this suite, and so does a model that learns a host it used to miss — until the
 * pin is updated. A bug list that cannot go stale is a bug list nobody trusts.
 *
 * ## Why a packaged build is graded differently
 *
 * `npm run package:extension` replaces these files with 30,000 hosts compiled from the desktop
 * hub's own blocklist. The model's blind spot is documented to cover roughly a third of a real
 * list, so demanding agreement with an arbitrary slice of someone's blocklist would fail for a
 * reason nobody can act on. In that state the size-independent guarantees are asserted instead —
 * they are not skipped, and the curated-baseline suite is reported as skipped rather than passing
 * without having checked anything.
 */

import { describe, expect, test } from '@jest/globals';
import { existsSync, readFileSync } from 'node:fs';
import { MiniAiClassifier } from '@blockingmachine/core/domain-ai';
import {
  STATIC_RULE_TIERS,
  tierById,
  tierCompilationSource,
  type StaticTierId,
} from '../shared/rulesetTiers.js';
// Core's derived vocabulary, read from source so the pin below cannot diverge from the record it is
// taken from. The module is generated by `scripts/derive-tier-vocabulary.mjs`, and
// `tierVocabularyDerivation.test.ts` re-derives it from these tiers and fails if the two disagree.
import { TIER_VOCABULARY_REJECTIONS } from '../../../core/src/ai/tierVocabulary.generated.js';
import { TIER_MODEL_FAMILIES } from '../../../core/src/ai/tierVocabularyDerivation.js';

type Category = ReturnType<MiniAiClassifier['classify']>['category'];

/** Blocking families: what the model says when it *has* placed a host. */
const BLOCKING_FAMILIES: readonly Category[] = [
  'Advertising',
  'Telemetry/Analytics',
  'Consent/Annoyance',
  'CNAME Cloaking',
];

/**
 * The families each tier may legitimately be called, imported from core rather than restated.
 *
 * The vocabulary these tiers teach the classifier is derived under this same table —
 * `tier_core`/`tier_privacy` accept any blocking family because ad and tracking infrastructure is
 * the point of both; `tier_ads` accepts only `Advertising`; `tier_annoyances` accepts only
 * `Consent/Annoyance`, so a consent vendor filed as telemetry is a misfile the derivation refuses
 * to launder rather than the nearest true answer; and `tier_security` is the inverted tier, whose
 * allowed family is `Malware/Phishing` because its contents are the model's own malware verdicts.
 *
 * Two copies of "what agreement means" is exactly the drift this suite exists to catch, so there is
 * one. Core's own comment on the table carries the per-tier reasoning.
 */
const TIER_FAMILIES: Partial<Record<StaticTierId, readonly Category[]>> = TIER_MODEL_FAMILIES;

/**
 * Hosts the model does not recognise, read out of the vocabulary's own refusal record.
 *
 * This list used to be typed here by hand, one entry per host somebody had investigated, and it was
 * the part that went stale in both directions: a vendor added to a tier showed up as a missing
 * entry, and a model that later learned a vendor showed up as an entry that had to be deleted by
 * whoever noticed. It is now taken from `tierVocabulary.generated.ts`, where
 * `scripts/derive-tier-vocabulary.mjs` records every host in the disagreement set that no derived
 * token could place — with the reason, and every candidate it tried, beside it.
 *
 * Every entry is a verdict the tier's contract cannot accept, and the record distinguishes the two
 * kinds: a `Clean` miss, where the model declines to have an opinion below the assertion mark; and
 * a *documented re-filing*, where the model places the host under a family stricter than the tier's
 * name — `onesignal.com` reads `Telemetry/Analytics` because the tracker-network evidence predates
 * and outranks the consent vocabulary. A re-filing is tolerable only because the record carries the
 * family it measured: the suite asserts the measured verdict is the one the derivation saw, so the
 * pin cannot silently absorb a genuinely different contradiction.
 *
 * ## Why the derivation's refusals are the same set this suite measures
 *
 * They are two different walks — the derivation seeds from the disagreement set under the
 * *hand-written* vocabulary, this suite measures under the *shipped* one — so the equality is a
 * consequence rather than a coincidence, and it is worth stating:
 *
 *   - The shipped vocabulary is the hand-written vocabulary plus the derived tokens, so anything the
 *     model places under the hand-written lists it still places. This suite therefore disagrees
 *     about no more hosts than the derivation seeded on.
 *   - The derivation only records a refusal for a host no derived token placed, which is exactly a
 *     host this suite still sees as a disagreement.
 *   - So a host can be in one set without the other only if the derivation contradicted itself, and
 *     either direction is a failure worth having: an unexplained disagreement, or a refusal that has
 *     outlived its reason.
 *
 * Three hosts are left, for two different reasons, and the record says which is which:
 *
 *   - `business-api.tiktok.com` — the only candidate that moved it (`tiktok`) was refused by the
 *     labelled corpus, because installing it would also have called `tiktok.com` an ad host. The
 *     token the endpoint *does* carry, `business-api.tiktok`, is hand-written, and it does move this
 *     host's telemetry probability (0.04 → 0.12) without moving the verdict: the `-api` label makes
 *     the infrastructure pass classify it as a product endpoint on a readable domain, and that
 *     precedence outranks every token in the model by design. An API zone on a major platform is
 *     exactly the shape a naive token match gets wrong, so the record stays as it is.
 *   - `privy.com` — no label of the name survives the vocabulary rules: `privy` is an ordinary
 *     English word, so it is refused as a token however many consent vendors are called it.
 *   - `onesignal.com` — the documented re-filing, and the one pinned disagreement that is not a
 *     `Clean` verdict. `onesignal` has been a hand-written tracker token longer than the consent
 *     category has existed, and the model's telemetry claim outranks the consent axis the consent
 *     candidates were tried under. The tier pins it as user-experience nuisance infrastructure
 *     (push-notification prompts); the model answers what the host *is*, and "push-engagement
 *     tracker" is that answer — a different facet of the same host rather than a contradiction.
 */
const TOLERATED_MISSES: Partial<Record<StaticTierId, readonly string[]>> = (() => {
  const pin: Partial<Record<StaticTierId, string[]>> = {};
  for (const rejection of TIER_VOCABULARY_REJECTIONS) {
    (pin[rejection.tier] ??= []).push(rejection.host);
  }
  return pin;
})();

/**
 * Confidence at or above which a `Clean` verdict stops being a shrug and becomes an assertion.
 *
 * "I cannot place this host" is tolerable in a hand-curated list; "this host is definitively clean"
 * is not, because the extension is blocking it anyway. Measured ceiling across every curated host
 * is 88%.
 */
const MAX_TOLERATED_CLEAN_CONFIDENCE = 90;

interface TierMeasurement {
  tier: StaticTierId;
  label: string;
  hosts: string[];
  /** Hosts whose family is not one the tier may be called. */
  disagreements: string[];
  /**
   * Disagreements where the model placed the host in a *different* family with no pin explaining
   * it — a contradiction. A pinned non-clean disagreement is a documented re-filing instead.
   */
  contradictions: string[];
  /** Disagreements reported as `Clean` at or above the assertion mark. */
  confidentClean: string[];
  /** Hosts the model considers malware or phishing. */
  malicious: string[];
  recognized: number;
  /** Highest confidence the model attached to a `Clean` verdict about a blocked host. */
  maxCleanConfidence: number;
}

/** Extracts the blocked host from `||host^` / `||host/path`, the only shapes a tier may ship. */
function hostsIn(tier: StaticTierId): string[] {
  const path = new URL(`../../rules/${tier}.json`, import.meta.url);
  if (!existsSync(path)) {
    throw new Error(
      `tier ruleset ${path.pathname} is missing — restore the curated baseline or run ` +
        '`npm run compile:tiers`; a manifest pointing at a missing ruleset is a broken build',
    );
  }

  const rules = JSON.parse(readFileSync(path, 'utf8')) as Array<{
    condition?: { urlFilter?: string };
  }>;
  if (!Array.isArray(rules)) throw new Error(`${path.pathname} is not a rule array`);

  const hosts = new Set<string>();
  for (const rule of rules) {
    const filter = rule?.condition?.urlFilter;
    if (typeof filter !== 'string' || !filter.startsWith('||')) continue;
    const host = filter.slice(2).split(/[/^$]/)[0].toLowerCase();
    if (host.includes('.')) hosts.add(host);
  }
  return [...hosts].sort();
}

function measureTier(tier: StaticTierId): TierMeasurement {
  const label = tierById(tier)?.label ?? tier;
  const allowed = TIER_FAMILIES[tier] ?? [];
  const pinned = new Set(TOLERATED_MISSES[tier] ?? []);
  // A private instance: no prediction cache shared with, or feedback from, any other test.
  const classifier = new MiniAiClassifier();
  const hosts = hostsIn(tier);

  const disagreements: string[] = [];
  const contradictions: string[] = [];
  const confidentClean: string[] = [];
  const malicious: string[] = [];
  let recognized = 0;
  let maxCleanConfidence = 0;

  for (const host of hosts) {
    const prediction = classifier.classify(host);
    if (prediction.category === 'Malware/Phishing') malicious.push(host);
    if (BLOCKING_FAMILIES.includes(prediction.category)) recognized += 1;
    if (allowed.includes(prediction.category)) continue;

    disagreements.push(host);
    if (prediction.category === 'Clean') {
      maxCleanConfidence = Math.max(maxCleanConfidence, prediction.confidence);
      if (prediction.confidence >= MAX_TOLERATED_CLEAN_CONFIDENCE) confidentClean.push(host);
    } else if (!pinned.has(host)) {
      // A cross-family verdict the pin does not explain is a contradiction. A pinned one is a
      // documented re-filing, verified family-for-family against the derivation's own record below.
      contradictions.push(host);
    }
  }

  return {
    tier,
    label,
    hosts,
    disagreements,
    contradictions,
    confidentClean,
    malicious,
    recognized,
    maxCleanConfidence,
  };
}

const MEASURED: TierMeasurement[] = STATIC_RULE_TIERS.map((tier) => measureTier(tier.id));

/** True while the tier files are a hub compilation rather than the curated baseline. */
const COMPILED = tierCompilationSource() !== null;

/** Grading that only means something against the curated baseline. Reported as skipped otherwise. */
const baselineOnly = COMPILED ? describe.skip : describe;

const qualified = (tier: TierMeasurement, hosts: readonly string[]): string[] =>
  hosts.map((host) => `${tier.tier}: ${host}`);

describe('shipped tiers vs the Mini-AI classifier', () => {
  test('classifies every domain the shipped tiers contain', () => {
    const total = MEASURED.reduce((sum, tier) => sum + tier.hosts.length, 0);
    console.log(
      `[tiers vs model] ${COMPILED ? 'hub compilation' : 'curated baseline'}: ` +
        MEASURED.map((tier) => `${tier.label} ${tier.recognized}/${tier.hosts.length}`).join(', '),
    );

    // Every tier must contribute hosts, or the loader silently walked an empty file and every
    // assertion below would hold by vacuity — except the one tier that is *supposed* to be empty
    // until a classifier has run somewhere. Asserting non-empty for it would make a fresh
    // checkout fail for being fresh, and skipping the assertion for every tier would let a
    // genuinely lost baseline through.
    for (const tier of MEASURED) {
      if (tierById(tier.tier)?.curatedSeed === false) continue;
      expect(tier.hosts.length).toBeGreaterThan(0);
    }
    expect(total).toBeGreaterThanOrEqual(118);
  });

  test('ships nothing the model considers malware or phishing, except in the tier that is for them', () => {
    // Holds at any size: a tier presenting itself as ads, privacy, or consent must not be where a
    // malicious host lands — and `tier_core` is enabled on a fresh install, so it is held first.
    const core = MEASURED.filter((tier) => tier.tier === 'tier_core');
    expect(core.flatMap((tier) => qualified(tier, tier.malicious))).toEqual([]);
    if (COMPILED) return;

    const others = MEASURED.filter((tier) => tier.tier !== 'tier_security');
    expect(others.flatMap((tier) => qualified(tier, tier.malicious))).toEqual([]);
  });

  test('holds only malware and phishing verdicts in the tier built from them', () => {
    // The inverted invariant. `tier_security` carries the model's own output, so "the model
    // agrees with it" is not a check — but "it contains nothing the model does *not* call
    // malware" is a real one, and it is what stops the tier drifting into a general-purpose
    // blocklist that happens to be assembled by the model. An empty baseline satisfies it, which
    // is the honest state of a checkout where the classifier has never run.
    const security = MEASURED.find((tier) => tier.tier === 'tier_security')!;
    expect(qualified(security, security.disagreements)).toEqual([]);
    expect(tierById('tier_security')?.defaultEnabled).toBe(false);
  });

  test('recognises every host the always-on Core shield tier ships', () => {
    const core = MEASURED.find((tier) => tier.tier === 'tier_core')!;
    // Compiling is additive and never re-tiers a curated host, so the curated core hosts are
    // present and recognised whether these files are the baseline or a hub compilation.
    const curatedCoreHosts = tierById('tier_core')?.ruleCount ?? 0;
    expect(curatedCoreHosts).toBeGreaterThan(0);
    expect(core.recognized).toBeGreaterThanOrEqual(curatedCoreHosts);

    // With the baseline in place the tier is held to the strict version: no gaps at all, because
    // this is the one tier that ships enabled.
    if (COMPILED) return;
    expect(qualified(core, core.disagreements)).toEqual([]);
  });

  baselineOnly('graded against the curated baseline', () => {
    test('never contradicts a tier with a different family', () => {
      // The headline invariant, and the only failure here that is a defect rather than a gap: the
      // model placing a host in a *different* blocking family means the tier and the model disagree
      // about what the thing is, which no amount of extra confidence resolves.
      expect(MEASURED.flatMap((tier) => qualified(tier, tier.contradictions))).toEqual([]);
    });

    test('never asserts a blocked host is clean with high confidence', () => {
      // "I cannot place this" is tolerable in a curated list. "This host is definitively clean" is
      // not, because the extension is blocking it anyway.
      expect(MEASURED.flatMap((tier) => qualified(tier, tier.confidentClean))).toEqual([]);
      for (const tier of MEASURED) {
        expect(tier.maxCleanConfidence).toBeLessThan(MAX_TOLERATED_CLEAN_CONFIDENCE);
      }
    });

    test('records exactly the disagreements it tolerates', () => {
      for (const tier of MEASURED) {
        expect(new Set(tier.disagreements)).toEqual(new Set(TOLERATED_MISSES[tier.tier] ?? []));
      }

      // And the pin is kept honest: an entry that has started agreeing is a stale entry, which
      // means the model learned something and the record must be updated rather than left to rot.
      const measuredByTier = new Map(MEASURED.map((tier) => [tier.tier, tier]));
      const stale = (Object.keys(TOLERATED_MISSES) as StaticTierId[]).flatMap((tier) =>
        (TOLERATED_MISSES[tier] ?? [])
          .filter((host) => !measuredByTier.get(tier)!.disagreements.includes(host))
          .map((host) => `${tier}: ${host}`),
      );
      expect(stale).toEqual([]);
    });

    test('places the annoyance tier under its own consent category', () => {
      // The tier that used to define the vocabulary gap now defines a category: 20 of its 22 hosts
      // are `Consent/Annoyance`, placed by the consent vocabulary the tier itself seeded. The two
      // exceptions are the pin's, not silent holes — `privy.com` underivable and `onesignal.com`
      // re-filed as telemetry.
      const annoyances = MEASURED.find((tier) => tier.tier === 'tier_annoyances')!;
      const pinned = new Set(TOLERATED_MISSES.tier_annoyances ?? []);
      expect(annoyances.hosts.length).toBeGreaterThan(20);

      const classifier = new MiniAiClassifier();
      for (const host of annoyances.hosts) {
        if (pinned.has(host)) continue;
        expect([host, classifier.classify(host).category]).toEqual([host, 'Consent/Annoyance']);
      }
      expect(annoyances.disagreements).toEqual(TOLERATED_MISSES.tier_annoyances);
      // Still opt-in: what a fresh install interrupts is a product decision — consent prompts and
      // notification flows are things sites *need* to show some users — not a statement about
      // whether the model can account for the tier. It can, and does, above.
      expect(tierById('tier_annoyances')?.defaultEnabled).toBe(false);
    });

    test('pins every cross-family disagreement to the family the derivation recorded', () => {
      // A pinned disagreement is allowed to be non-clean only as a *documented* re-filing: the
      // rejection record carries the family the derivation measured, and the live classifier has
      // to agree with it. Without this check a pinned host could drift into any other family —
      // including a real contradiction — and the tolerance would silently absorb it.
      const classifier = new MiniAiClassifier();
      const rejectionsByHost = new Map(
        TIER_VOCABULARY_REJECTIONS.map((rejection) => [rejection.host, rejection]),
      );
      for (const tier of MEASURED) {
        for (const host of tier.disagreements) {
          const prediction = classifier.classify(host);
          if (prediction.category === 'Clean') continue;
          const rejection = rejectionsByHost.get(host)!;
          expect(rejection).toBeDefined();
          expect(
            rejection.attempts.map((attempt) => attempt.family),
          ).toContain(prediction.category);
        }
      }
    });
  });
});
