import type { SupportedFormat, FilterListMetadata } from "../types.js";
import { PRIVOXY_BLOCK_SECTION, RPZ_ZONE_PREAMBLE } from "./formatters.js";

/** Prevent metadata from terminating a comment and adding active filter rules. */
export function sanitizeHeaderMetadata(meta: FilterListMetadata): FilterListMetadata {
  const result = { ...meta };
  for (const key of ["title", "description", "homepage", "version", "lastUpdated", "expires", "author", "license", "generatorVersion"] as const) {
    const value = result[key];
    if (typeof value === "string") result[key] = value.replace(/[\x00-\x1f\x7f\u0085\u2028\u2029]+/g, " ");
  }
  return result;
}

export function generateHeader(
  meta: FilterListMetadata,
  format: SupportedFormat,
): string {
  meta = sanitizeHeaderMetadata(meta);
  const isBangComment =
    format === "adguard" || format === "abp" || format === "all";
  // A BIND response policy zone is a master file, not `named.conf`: its comment character is `;`,
  // and `#` there is a parse error rather than a comment.
  const c = isBangComment ? "! " : format === "bind" ? "; " : "# ";

  // Common header for all formats
  const commonHeader = [
    c + "Title: " + meta.title,
    c + "Description: " + meta.description,
    c + "Homepage: " + meta.homepage,
    c + "Version: " + meta.version,
    c + "Last updated: " + meta.lastUpdated,
  ];

  // Format-specific additions
  const additionalLines: string[] = [];

  switch (format) {
    case "hosts":
      additionalLines.push(
        c + "Format: Hosts",
        c +
          "This file is in hosts file format and can be used as system hosts file",
      );
      break;
    case "dnsmasq":
      additionalLines.push(
        c + "Format: dnsmasq",
        c + "This file contains rules suitable for dnsmasq DNS server",
      );
      break;
    case "unbound":
      additionalLines.push(
        c + "Format: Unbound",
        c + "This file contains rules suitable for Unbound DNS server",
      );
      break;
    case "bind":
      additionalLines.push(
        c + "Format: BIND Response Policy Zone (RPZ)",
        c + "One CNAME policy record per blocked name; CNAME . means NXDOMAIN.",
      );
      break;
    case "privoxy":
      additionalLines.push(
        c + "Format: Privoxy",
        c + "This file contains rules suitable for Privoxy proxy server",
      );
      break;
    case "shadowrocket":
      additionalLines.push(
        c + "Format: Shadowrocket",
        c + "This file contains rules suitable for Shadowrocket app",
      );
      break;
    case "adguard":
      additionalLines.push(
        c + "Format: AdGuard",
        c + "This file contains rules optimized for AdGuard products",
      );
      break;
    case "abp":
      additionalLines.push(
        c + "Format: ABP",
        c + "This file contains rules compatible with Adblock Plus",
      );
      break;
    case "all":
      additionalLines.push(
        c + "Format: All",
        c + "This file contains all rules in their original formats",
      );
      break;
  }

  // Add statistics if available
  if (meta.stats) {
    additionalLines.push(
      c + "Total Rules: " + (meta.stats.totalRules ?? "N/A"),
      c + "Blocking Rules: " + (meta.stats.blockingRules ?? "N/A"),
      c + "Exception Rules: " + (meta.stats.exceptionRules ?? "N/A"),
    );
  }

  // Add license and generator info
  additionalLines.push(
    c + "License: " + (meta.license || "Unspecified"),
    c + "Generated by Blockingmachine " + (meta.generatorVersion || ""),
    "", // Empty line at the end
  );

  if (format === "unbound") additionalLines.push("server:");
  // A Privoxy action file is section-based: every URL pattern belongs to the action block above
  // it, and a file that opens with bare patterns has no action to belong to. The block section is
  // opened here, after the comments and before the first pattern.
  if (format === "privoxy") additionalLines.push(PRIVOXY_BLOCK_SECTION);
  // A BIND primary zone does not load without an SOA, so the preamble is part of the artifact
  // rather than something the user is left to discover from a `no SOA` load failure.
  if (format === "bind") {
    additionalLines.push(
      c + "Add it to named.conf:",
      c + "  zone \"rpz.blockingmachine\" { type master; file \"db.blockingmachine.rpz\"; };",
      c + "and inside options { }:",
      c + "  response-policy { zone \"rpz.blockingmachine\"; };",
      c + "A child bypass is emitted as CNAME rpz-passthru., which wins on the longest match.",
      "",
      ...RPZ_ZONE_PREAMBLE.split("\n"),
    );
  }
  // A Shadowrocket/Surge config is INI-shaped: the rules live under a `[Rule]` section, and a
  // file that is nothing but `DOMAIN-SUFFIX,…` lines has nowhere to be read from. The app also
  // accepts a bare remote rule list, but a section header is what makes the same artifact valid
  // as a full config, so it is emitted rather than left to the user to add.
  if (format === "shadowrocket") additionalLines.push("[Rule]");
  return [...commonHeader, ...additionalLines].join("\n");
}
