# AGLint config file
# Documentation: https://github.com/AdguardTeam/AGLint#configuration
root: true
extends:
  - aglint:recommended
syntax:
  - AdGuard
rules:
  invalid-modifiers: off
  no-excluded-rules:
    - error
    - regexp-patterns:
        - ^\\s*\\w+\\s*\\$[\\w\\s]*$