/**
 * The curated table of known first-party-CNAME-cloaking destinations.
 *
 * Lives in its own module — not in `cnameResolver.ts` — because the *consumers* differ
 * in what they may import: `elementClassifier.ts` is bundled into content scripts where
 * a `node:dns` import cannot follow, and this table is the evidence its `cnameCloak`
 * feature reads. `cnameResolver` re-exports it, so the public surface is unchanged.
 *
 * An entry means "a DNS answer ending here is that provider" — matched as a registrable
 * suffix, exactly the way `isBenignCnameTarget` and the classifier both consume it.
 */

/**
 * Known third-party tracker, advertising exchange, audience DMP, affiliate network,
 * and anti-adblock CNAME cloaking destinations.
 * These providers use first-party DNS alias delegation to bypass browser cookie sandboxing
 * and DNS blockers.
 */
export const KNOWN_CLOAKED_TARGETS: Record<string, string> = {
  // Retargeting, Ad Exchanges & SSPs
  'criteo.com': 'Criteo Retargeting & Ad Exchange',
  'criteo.net': 'Criteo Retargeting & Ad Exchange',
  'criteo.org': 'Criteo Retargeting & Ad Exchange',
  'hlserve.com': 'Criteo Ad Delivery',
  'sc-cdn.net': 'Snapchat Ad Measurement',
  'snapchat.com': 'Snapchat Analytics',
  'adsrvr.org': 'The Trade Desk Unified ID CNAME Cloak',
  'adroll.com': 'AdRoll Retargeting',
  'd41.co': 'AdRoll CNAME Tracking',
  'rlcdn.com': 'LiveRamp IdentityLink Tracking Cloak',
  'liveramp.com': 'LiveRamp IdentityLink',
  'mathtag.com': 'MediaMath Ad Measurement',
  'mediamath.com': 'MediaMath Ad Platform',
  'openx.net': 'OpenX Ad Exchange',
  'openx.com': 'OpenX Ad Exchange',
  'pubmatic.com': 'PubMatic Ad Exchange',
  'rubiconproject.com': 'Magnite / Rubicon Ad Exchange',
  'smartadserver.com': 'Smart AdServer / Equativ',
  'triplelift.net': 'TripleLift Native Ads',
  'adnxs.com': 'AppNexus / Xandr Advertising',
  'adnxs.net': 'AppNexus / Xandr Advertising',
  'adform.net': 'Adform Ad Serving & Attribution Cloak',
  'adform.com': 'Adform Ad Platform',
  'flashtalking.com': 'Flashtalking Ad Serving Cloak',
  'yieldlab.net': 'Yieldlab Programmatic Exchange',
  'casalemedia.com': 'Index Exchange / Casale Media',
  'indexexchange.com': 'Index Exchange',
  'avocet.io': 'Avocet Programmatic DSP',
  'adgear.com': 'Samsung Ads / AdGear Ad Serving',
  'npttech.com': 'Neustar Platform Technologies Cloak',
  'sovrn.com': 'Sovrn / VigLink Affiliate Tracking',
  'viglink.com': 'Sovrn VigLink Affiliate Cloak',
  'tradedoubler.com': 'TradeDoubler Affiliate Tracking',
  'affilinet.de': 'Affilinet / Awin Affiliate Cloak',
  'effiliation.com': 'Effiliation Affiliate Tracking',
  'belboon.com': 'Belboon Affiliate Network',
  'zanox.com': 'Zanox Affiliate Tracking',
  'webgains.com': 'Webgains Affiliate Tracking',
  'c3tag.com': 'Commanders Act C3 Tag Cloak',
  'ensighten.com': 'Ensighten Tag Management Cloak',
  'tealiumiq.com': 'Tealium iQ Tag Management Cloak',
  'tiqcdn.com': 'Tealium Tag CDN Cloak',
  'adzerk.net': 'Kevel / Adzerk API Ad Serving',
  'kevel.co': 'Kevel Ad Serving Cloak',
  'c1exchange.com': 'Clearstream / C1 Ad Exchange',
  'gumgum.com': 'GumGum Contextual Ad Server',
  'undertone.com': 'Undertone High Impact Ads',
  'inmobi.com': 'InMobi Mobile Ad Network',
  'ironsrc.com': 'ironSource / Unity Ads Cloak',
  'vungle.com': 'Liftoff / Vungle Video Ads',
  'applovin.com': 'AppLovin Mobile Ad Network',
  'chartboost.com': 'Chartboost Gaming Ad Network',
  'smaato.net': 'Smaato Mobile Ad Exchange',
  'fyber.com': 'Digital Turbine / Fyber Ad Exchange',
  'spotxchange.com': 'SpotX Video Ad Exchange',
  'spotx.tv': 'SpotX Video Ad Exchange',
  'connatix.com': 'Connatix Video Monetization Cloak',
  'primis.tech': 'Primis Video Discovery Cloak',
  'exelator.com': 'eXelate / Nielsen DMP',
  'visualdna.com': 'VisualDNA / Nielsen Consumer Insights',
  'semasio.net': 'Semasio Behavioral Targeting Cloak',
  'eyeota.net': 'Eyeota Audience Data Cloak',
  'bombora.com': 'Bombora B2B Intent Telemetry',
  'id5-sync.com': 'ID5 Universal ID Identity Tracking',
  'sharedid.org': 'Prebid SharedID Ad Tracking',
  'pro-market.net': 'Datonics Ad Targeting',
  'turn.com': 'Amobee / Turn DSP',
  'zemanta.com': 'Outbrain Zemanta Native DSP',
  'nativo.com': 'Nativo Sponsored Content Ad Platform',
  'stackadapt.com': 'StackAdapt Programmatic Advertising',
  'viantinc.com': 'Viant / Adelphic DSP',
  'chango.com': 'Rubicon Chango Retargeting',
  'distroscale.com': 'DistroScale Video Advertising',
  'aniview.com': 'Aniview Video Ad Server',

  // Telemetry, Attribution & Mobile Deep Linking
  'branch.io': 'Branch Metrics Deep Linking Tracker',
  'app.link': 'Branch Metrics Deep Linking Tracker',
  'go.link': 'Branch Metrics Tracker',
  'bnc.lt': 'Branch Metrics Short Link Tracker',
  'keywee.co': 'Keywee Content Telemetry & Audience Tracker',
  'dnsdelegation.io': 'Keywee Content Tracker Cloak',
  'eulerian.net': 'Eulerian Data Analytics',
  'eulerian.com': 'Eulerian Data Analytics',
  'affilae.com': 'Affilae Affiliate Tracker',
  'wizaly.com': 'Wizaly Attribution Platform',
  'commandersact.com': 'Commanders Act CDP',
  'tagcommander.com': 'Commanders Act Tag Commander',
  'at-o.net': 'AT Internet / Piano Analytics',
  'atinternet.net': 'AT Internet Analytics',
  'piano.io': 'Piano Analytics & Paywall Telemetry',
  'wt-eu02.net': 'Mapp Intelligence / Webtrekk',
  'webtrekk.net': 'Webtrekk Telemetry',
  'wt-safetag.com': 'Webtrekk / Mapp SafeTag Cloak',
  'omtrdc.net': 'Adobe Audience Manager / Experience Cloud',
  'demdex.net': 'Adobe Audience Manager',
  'everesttech.net': 'Adobe Advertising Cloud',
  '2o7.net': 'Adobe Omniture Tracking',
  'adobedc.net': 'Adobe Experience Platform Edge CNAME Cloak',
  'auditude.com': 'Adobe Primetime Ad Serving',
  'omniture.com': 'Adobe Omniture Analytics',
  'exacttarget.com': 'Salesforce Marketing Cloud Telemetry',
  'krux.net': 'Salesforce Krux DMP',
  'pardot.com': 'Salesforce Pardot Marketing Tracker',
  'actonsoftware.com': 'Act-On Marketing Automation Tracker',
  'hubspot.net': 'HubSpot Tracking Domain',
  'hs-analytics.net': 'HubSpot Analytics CNAME Cloak',
  'sail-horizon.com': 'Sailthru Email & Conversion Tracker',
  'bounceexchange.com': 'Wunderkind / BounceX Behavioral Tracker',
  'wunderkind.co': 'Wunderkind Behavioral Tracker',
  'yieldify.com': 'Yieldify Conversion Telemetry',
  'sl-edge.com': 'Smartlook Analytics Edge',
  'adlooxtracking.com': 'Adloox Verification & Tracking',
  's-onetag.com': 'Sharethrough Tag / Tracker',
  'awin1.com': 'Awin Affiliate Tracker',
  'linksynergy.com': 'Rakuten LinkShare Affiliate Tracker',
  'impactradius.com': 'Impact Affiliate Tracker',
  'segment.io': 'Segment Customer Data Platform',
  'marketo.com': 'Adobe Marketo Lead Tracker',
  'mktoresp.com': 'Adobe Marketo Lead Tracking Cloak',
  'appsflyer.com': 'AppsFlyer Attribution',
  'onelink.me': 'AppsFlyer OneLink Tracker',
  'singular.net': 'Singular ROI Tracking',
  'adjust.com': 'Adjust Mobile Measurement Tracker',
  'adj.st': 'Adjust Mobile Deep Link Tracker',
  'kochava.com': 'Kochava Attribution & Analytics Engine',
  'trackcmp.net': 'ActiveCampaign Telemetry & Tracking',
  'bluekai.com': 'Oracle BlueKai DMP',
  'crwdcntrl.net': 'Lotame Audience DMP Cloak',
  'lotame.com': 'Lotame Data Management Platform',
  'moatads.com': 'Oracle Moat Ad Measurement',
  'oracleinfinity.io': 'Oracle Infinity Analytics',
  'eloqua.com': 'Oracle Eloqua Marketing Automation',
  'agkn.com': 'Neustar / Fabrick Identity Resolution',
  'permutive.com': 'Permutive Edge Publisher DMP',
  'permutive.app': 'Permutive Edge DMP',
  'taboola.com': 'Taboola Recommendation Widget Tracker',
  'outbrain.com': 'Outbrain Recommendation Tracker',
  'trc.taboola.com': 'Taboola Telemetry',

  // Session Replay & Behavioral Telemetry
  'crazyegg.com': 'Crazy Egg Heatmap & Session Tracking',
  'mouseflow.com': 'Mouseflow Behavioral Session Tracking',
  'clicktale.net': 'Contentsquare / Clicktale Session Replay',
  'contentsquare.net': 'Contentsquare Digital Experience Telemetry',
  'hotjar.com': 'Hotjar Behavioral Heatmap & Telemetry',
  'luckyorange.net': 'Lucky Orange Session Replay Cloak',
  'fullstory.com': 'FullStory Session Recording & Telemetry',
  'clarity.ms': 'Microsoft Clarity Behavioral Telemetry',
  'inspectlet.com': 'Inspectlet User Session Recording',
  'decibelinsight.net': 'Medallia Decibel Session Recording',
  'qualtrics.com': 'Qualtrics Site Intercept Telemetry',

  // Anti-Adblock & Paywall Bypass Providers
  'admiraldrm.com': 'Admiral Anti-Adblock & Paywall Bypass',
  'getadmiral.com': 'Admiral Anti-Adblock & Paywall Bypass',
  'admiralservices.com': 'Admiral Anti-Adblock & Paywall Bypass',
  'admiralcloud.com': 'Admiral Anti-Adblock & Paywall Bypass',
  'carter-carrier.com': 'Admiral Anti-Adblock Dynamic Cloak',
  'whisperingwax.com': 'Admiral Anti-Adblock Dynamic Cloak',
  'chiseledcherry.com': 'Admiral Anti-Adblock Dynamic Cloak',
  'defiantdigital.com': 'Admiral Anti-Adblock Dynamic Cloak',
  'spitefulsoup.com': 'Admiral Anti-Adblock Dynamic Cloak',
  'sylvansteam.com': 'Admiral Anti-Adblock Dynamic Cloak',
  'btloader.com': 'BlockThrough Anti-Adblock Bypass',
  'blockthrough.com': 'BlockThrough Anti-Adblock Bypass',
  'pagefair.com': 'PageFair Anti-Adblock Bypass',
  'pagefair.net': 'PageFair Anti-Adblock Bypass',
  'adinplay.com': 'AdInPlay Anti-Adblock Bypass',
  'adinplay.bid': 'AdInPlay Anti-Adblock Bypass',
  'adinplay.eu': 'AdInPlay Anti-Adblock Bypass',
  'fundingchoicesmessages.google.com': 'Google Funding Choices Anti-Adblock',
  'fc.yahoo.com': 'Google Funding Choices / Yahoo Consent Anti-Adblock',
  'ezodn.com': 'Ezoic Ad-Recovery CNAME Cloak',
  'ezoiccdn.com': 'Ezoic Ad-Recovery CNAME Cloak',
  'snigelweb.com': 'Snigel Ad-Recovery CNAME Cloak',
  'snigel.com': 'Snigel Ad-Recovery Platform',
  'bolt.playwire.com': 'Playwire Ad-Recovery CNAME Cloak',
  'adtoniq.com': 'AdToniq Anti-Adblock Bypass',
  'addefend.com': 'AdDefend Anti-Adblock Bypass',
  'instartlogic.com': 'Instart Logic Anti-Adblock Cloak',
  'instart.com': 'Instart Anti-Adblock Cloak',
};
