name: AgLint
permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  wait-for-update-filters:
    name: Wait for Update Filters
    runs-on: ubuntu-latest
    steps:
      - run: echo "Waiting for update-filters workflow to complete"

  aglint:
    name: AdGuard Lint
    runs-on: ubuntu-latest
    needs: wait-for-update-filters
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # Enable npm caching

      - name: Clean Install
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          npm ci

      - name: Run AdGuard Linter
        run: npm run aglint
