name: ESLint
permissions: write-all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # Enable npm caching

      - name: Clean Install
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          npm ci

      - name: Run ESLint
        run: npm run eslint

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - eslint
    if: always()
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: GitHub Actions
          avatar-url: https://avatars0.githubusercontent.com/u/44036562?s=200&v=4
          include-details: true
          color-success: 17cf48
          color-failure: e72727
          color-cancelled: d3d3d3
