name: Primary Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-txt-files:
    name: Update TXT Files
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run update script
        run: npm run start

      - name: Check for changes
        id: git_diff
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --exit-code || echo "changes" > changes.txt

      - name: Commit and push changes
        if: steps.git_diff.outputs.changes == 'changes'
        run: |
          git commit -m "Update .txt files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: npm run mdlint

  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run eslint

  aglint:
    name: Run AGLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run AGLint
        run: npm run aglint

  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website # Adjust this path to your website directory
          publish_branch: gh-pages

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: 
      - update-txt-files
      - markdownlint
      - eslint
      - aglint
      - deploy-website
    if: ${{ failure() }} # Only notify on failure
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: GitHub Actions
          avatar-url: https://avatars0.githubusercontent.com/u/44036562?s=200&v=4
          include-details: true
          color-success: 17cf48
          color-failure: e72727
          color-cancelled: d3d3d3