name: Daily Updates

on:
  schedule:
    - cron: "0 0 * * *" # Run at midnight UTC
  workflow_dispatch: # Allow manual triggers

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run version

      - name: Commit README update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
            git diff --quiet && git diff --staged --quiet || (git commit -m "Update last updated timestamp [skip ci]" && git push)
